
####################################################################################
# Generated by Vivado 2017.2 built on 'Thu Jun 15 18:39:09 MDT 2017' by 'xbuild'
# Command Used: write_xdc -force Stopwatch.xdc
####################################################################################


# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
